services:
  spark-master:
    image: apache/spark-py
    command: start-master.sh
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      my-network:
        ipv4_address: 10.0.0.2

  spark-worker-1:
    image: apache/spark-py
    command: start-worker.sh spark://spark-master:7077
    depends_on:
      - spark-master
    deploy:
      replicas: 1
    networks:
      my-network:
        ipv4_address: 10.0.0.3

  spark-worker-2:
    image: apache/spark-py
    command: start-worker.sh spark://spark-master:7077
    depends_on:
      - spark-master
    deploy:
      replicas: 1
    networks:
      my-network:
        ipv4_address: 10.0.0.4

  jupyter:
    image: jupyter/pyspark-notebook
    command: start-notebook.sh
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    networks:
      my-network:
        ipv4_address: 10.0.0.5

  minio:
    image: minio/minio
    command: server /data
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    volumes:
      - D:/docker/local/wsl/mtm/disk02/minio_data:/data  # Usando caminho no host
    networks:
      my-network:
        ipv4_address: 10.0.0.6

networks:
  my-network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/16

